language: java
jdk:
  - openjdk11

# TO DO:
#addons:
#  sonarcloud:
#    organization: awt-05
#    token: "${SONAR_TOKEN}"

script:
  - ./gradlew clean check -x test
#  - ./gradlew check
#  - sonar-scanner/piKey=$API_KEY -PapiToken=$API_TOKEN -PfilterTags=@functional

notifications:
  email: false
