#sudo: required

language: java
jdk:
  - openjdk11

#addons:
#  sonarcloud:
#    organization: awt-05
#    token: "${SONAR_TOKEN}"

script:
#  - chmod +x gradlew
  - ./gradlew check
#  - sonar-scanner/piKey=$API_KEY -PapiToken=$API_TOKEN -PfilterTags=@functional

notifications:
  email: false
