language: java
jdk:
  - openjdk11

# TO DO: addons: sonarcloud

script:
  - ./gradlew clean check -x test
# TO DO: sonar-scanner

notifications:
  email: true

before_install:
  - openssl aes-256-cbc -K $encrypted_355e94ba1091_key -iv $encrypted_355e94ba1091_iv
    -in super_secret.txt.enc -out super_secret.txt -d
