language: java
jdk:
  - openjdk11

script:
  - ./gradlew check
  - ./gradlew executeBDDTests -PbrowserName=headless -PcucumberThreadCount=1

notifications:
  email: true
before_install:
- openssl aes-256-cbc -K $encrypted_c5fd3201494e_key -iv $encrypted_c5fd3201494e_iv
  -in config.json.enc -out config.json -d
